### ISSUE TITLE
Some questions about the experiment in the paper on MICCAI2022 "Structure-Consistent Restoration Network for Cataract Fundus Image Enhancement"

### ISSUE THREAD

**Issue by Nimbus2002** [liamheng/Annotation-free-Fundus-Image-Enhancement#1]
Hello, first thank you for providing the code :) I read your paper "Structure-Consistent Restoration Network for Cataract Fundus Image Enhancement" on MICCAI 2022! Nice paper👍

I have some questions about the experiment in the paper,
1. About the ablation study you conducted, I don't get how you did that. 
Because the input of SCR-Net is H(S'k), a high frequency of SCS, how could you run your code without using SCS nor H()? is it even possible to train your model without them?
![image](https://user-images.githubusercontent.com/66589193/215329464-b5619758-9233-469a-a4dd-1c5be77adcf2.png)
![image](https://user-images.githubusercontent.com/66589193/215329484-9149531c-af96-42d2-926a-6cfd611e9367.png)

2. About the training process, how did you set stopping criteria? I am doing a similar project and want to have some intuition into how the published paper writer stopped training.

Thank you in advance! 
Hope you have a good day,
Sincerely, Ellen

**Comment by liamheng** [comment]
@HeverLaw

**Comment by HeverLaw** [comment]
1. In the ablation study, you can adjust the input dimension to 3 in order to process RGB-only images, which allows you to train a new model specifically for this purpose.
2. We continue training until the predefined number of epochs is reached. To select the best model, we evaluate it using synthetic fundus images from the evaluation dataset. Generally, the model achieves the best performance close to the end of the training process.
