### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Huangqqqhhh** [liamheng/Annotation-free-Fundus-Image-Enhancement#4]
source域和target域是一起训练的嘛，如果是，那么我如何去修复一张未经过放入targret域中训练的白内障眼底图像照片？

**Comment by Railies** [comment]
你好，我也在关注这个项目，可以交流一下吗

**Comment by Huangqqqhhh** [comment]
可以的


&nbsp;


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月1日(星期三) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liamheng/Annotation-free-Fundus-Image-Enhancement] demo (Issue #4)





 
你好，我也在关注这个项目，可以交流一下吗

**Comment by Huangqqqhhh** [comment]
你的联系方式是什么&nbsp;


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月1日(星期三) 上午9:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liamheng/Annotation-free-Fundus-Image-Enhancement] demo (Issue #4)





 
你好，我也在关注这个项目，可以交流一下吗

**Comment by Railies** [comment]
抱歉，看不到您的联系方式。我的邮箱:2937898618@qq.com

**Comment by Huangqqqhhh** [comment]
***@***.***
&nbsp;


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 上午10:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liamheng/Annotation-free-Fundus-Image-Enhancement] demo (Issue #4)





 
抱歉，看不到您的联系方式

**Comment by Railies** [comment]
额，你的邮箱被*打码了

**Comment by Huangqqqhhh** [comment]
我加你QQ了

&nbsp;


权是海
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年11月6日(星期一) 中午11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [liamheng/Annotation-free-Fundus-Image-Enhancement] demo (Issue #4)





 
额，你的邮箱被*打码了

**Comment by HeverLaw** [comment]
It depends on what model you are using. ArcNet is trained with source data with ground truth and target data without ground truth, so you need to fine-tune or retrain a new model using the source and target data, note that you should add some of the real low-quality images into the target dataset to get a desirable result. However, in SCR-Net and GFE-Net, you don't need to retrain the model, since it can generalize well to unseen images with the desired preprocess.
