### ISSUE TITLE
Hello, I would like to know why this error occurred.

### ISSUE THREAD

**Issue by qihuiyan1023** [liamheng/Annotation-free-Fundus-Image-Enhancement#5]
ModuleNotFoundError: No module named data.unaligned_dataset

**Comment by liamheng** [comment]
@HeverLaw

**Comment by HeverLaw** [comment]
This error is because you did not specify a dataset. In our code, you can use -- dataset_mode catalact_with_mask. Please enter the corresponding command before running the code, for example, if you want to train GFE Net, enter Python train.py -- dataroot/ images/cataract_dataset --name train_gfenet --model gfenet --direction AtoB --dataset_mode cataract_with_mask --norm instance --batch_size 8 --gpu_ids 2 --lr_policy linear --n_epochs 150 --n_epochs_decay 50.
